"""HelperBot Initial revision 1

Revision ID: 08eebfd12ad7
Revises: 
Create Date: 2024-10-06 19:59:53.810485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08eebfd12ad7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    op.create_table('temporary_conference_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.String(length=320), nullable=True),
    sa.Column('office', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.String(length=320), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('illegal_intervals', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    op.create_table('temporary_events_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('type_event', sa.String(length=128), nullable=False),
    sa.Column('office', sa.String(length=128), nullable=True),
    sa.Column('info', sa.String(length=2048), nullable=True),
    sa.Column('delivery_rate', sa.String(length=128), nullable=True),
    sa.Column('taxi_rate', sa.String(length=128), nullable=True),
    sa.Column('departure_address', sa.String(length=256), nullable=True),
    sa.Column('destination_address', sa.String(length=256), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('tracking_flag', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tg', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=320), nullable=False),
    sa.Column('fullname', sa.String(length=320), nullable=False),
    sa.Column('fio', sa.String(length=320), nullable=False),
    sa.Column('date_reg', sa.DateTime(), nullable=False),
    sa.Column('number_created_conferences', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    op.create_table('created_conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.TIMESTAMP(), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('office', sa.String(length=320), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['helper_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    op.create_table('created_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.TIMESTAMP(), nullable=False),
    sa.Column('type_event', sa.String(length=128), nullable=False),
    sa.Column('office', sa.String(length=128), nullable=True),
    sa.Column('info', sa.String(length=2048), nullable=True),
    sa.Column('delivery_rate', sa.String(length=128), nullable=True),
    sa.Column('taxi_rate', sa.String(length=128), nullable=True),
    sa.Column('departure_address', sa.String(length=256), nullable=True),
    sa.Column('destination_address', sa.String(length=256), nullable=True),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('tracking_flag', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['helper_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    op.create_table('user_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id_topic_chat', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['helper_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='helper_bot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chats', schema='helper_bot')
    op.drop_table('created_events', schema='helper_bot')
    op.drop_table('created_conferences', schema='helper_bot')
    op.drop_table('users', schema='helper_bot')
    op.drop_table('temporary_events_data', schema='helper_bot')
    op.drop_table('temporary_conference_data', schema='helper_bot')
    op.drop_table('admin_group', schema='helper_bot')
    # ### end Alembic commands ###
